[package]
name = "auth_jwt"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"

argon2 = "0.5.3"
jsonwebtoken = "9.3.1"

serde = { version = "1.0.219", features = ["derive"] }


sqlx = { version = "0.8.6", features = [
    "postgres",
    "runtime-tokio",
    "tls-native-tls",
] }
